### ISSUE TITLE
Minimap Pins

### ISSUE THREAD

**Issue by abhi-arya1** [Team-Cartographer/SUITS-2024-HMD#8]
The DE must be able to drop pins which become visible in the AR environment as well as on the minimap and on the LMCC.
Pins dropped by the LMCC must also show up in the minimap for HMD and AR environment

**Comment by a1-Raza** [comment]
Hoping to get further details about LMCC's integration when they're ready for it, but for now I'll implement the pins to be visible at the spot it was placed on the terrain, as well as on the minimap
